import java.util.HashMap;
import java.util.Map;

public class CodeFormats {
    final public static Map<String, String> COUN_MAP = new HashMap<String, String>(){{
        put("Albania", "10YAL-KESH-----5");
        put("Armenia", "10Y1001A1001B004");
        put("Austria", "10YAT-APG------L");
        put("Azerbaijan", "10Y1001A1001B05V");
        put("Belarus", "BY"         );
        put("Belgium", "10YBE----------2");
        put("Bosnia and Herz.", "10YBA-JPCC-----D");
        put("Bulgaria", "10YCA-BULGARIA-R");
        put("Croatia", "10YHR-HEP------M");
        put("Cyprus", "10YCY-1001A0003J");
        put("Czech Republic", "10YCZ-CEPS-----N");
        put("Denmark", "10Y1001A1001A65H");
        put("Estonia", "10Y1001A1001A39I");
        put("Finland", "10YFI-1--------U");
        put("France", "10YFR-RTE------C");
        put("Georgia", "10Y1001A1001B012");
        put("Germany", "10Y1001A1001A83F");
        put("Greece", "10YGR-HTSO-----Y");
        put("Hungary", "10YHU-MAVIR----U");
        put("Iceland ","IS");
        put("Ireland", "10YIE-1001A00010");
        put("Italy", "10YIT-GRTN-----B");
        put("Kosovo", "10Y1001C--00100H");
        put("Latvia", "10YLV-1001A00074");
        put("Lithuania", "10YLT-1001A0008Q");
        put("Luxembourg", "10YLU-CEGEDEL-NQ");
        put("Malta ","10Y1001A1001A93C");
        put("Moldova", "10Y1001A1001A990");
        put("Montenegro", "10YCS-CG-TSO---S");
        put("Netherlands", "10YNL----------L");
        put("North Macedonia", "10YMK-MEPSO----8");
        put("Norway", "10YNO-0--------C");
        put("Poland", "10YPL-AREA-----S");
        put("Portugal", "10YPT-REN------W");
        put("Romania", "10YRO-TEL------P");
        put("Russia", "RU");
        put("Serbia", "10YCS-SERBIATSOV");
        put("Slovakia", "10YSK-SEPS-----K");
        put("Slovenia", "10YSI-ELES-----O");
        put("Spain", "10YES-REE------0");
        put("Sweden", "10YSE-1--------K");
        put("Switzerland", "10YCH-SWISSGRIDZ");
        put("Turkey", "10YTR-TEIAS----W");
        put("Ukraine", "10Y1001C--00003F");
        put("United Kingdom","10Y1001A1001A92E");
    }};

    final public static Map<String, String> ENERGY_MAP = new HashMap<String, String>(){{
        put("Mixed","A03");
        put("Generation","A04");
        put("Load","A05");
        put("Biomass","B01");
        put("Fossil Brown coal/Lignite","B02");
        put("Fossil Coal-derived gas","B03");
        put("Fossil Gas","B04");
        put("Fossil Hard coal","B05");
        put("Fossil Oil","B06");
        put("Fossil Oil shale","B07");
        put("Fossil Peat","B08");
        put("Geothermal","B09");
        put("Hydro Pumped Storage","B10");
        put("Hydro Run-of-river and poundage","B11");
        put("Hydro Water Reservoir","B12");
        put("Marine","B13");
        put("Nuclear","B14");
        put("Other renewable","B15");
        put("Solar","B16");
        put("Waste","B17");
        put("Wind Offshore","B18");
        put("Wind Onshore","B19");
        put("Other","B20");
        put("AC Link","B21");
        put("DC Link","B22");
        put("Substation","B23");
        put("Transformer","B24");
    }};
}
